cmake:transcalc remove libtranscalc
It calls methods from qucstrans.cpp, but is not linked against that:
ld: CMakeFiles/transcalc.dir/transline.cpp.o: in function `transline::setProperty(char const*, double)':
qucs/qucs-transcalc/transline.cpp:76: undefined reference to `QucsTranscalc::setProperty(QString, double)'
and so on...

AFAICT, the library is not needed at all (it actually cannot be used,
the symbols from qucstrans.cpp would be missing), so remove it
completely.