Fix component-from-library-lookup error message
ERROR: "someinstance": could not load "somemodel" from "somelib"

instead of

ERROR: "someinstance": bad.