error: expected unqualified-id before numeric constant
Not sure, maybe lst2 and lst3 are defined elsewhere.
Renaming seem to work.

System: Windows / MSYS2 / CMake/ Qt 511.1 / GCC 7.3.