qucsVersion: fix analog function derivative name
Error:
bsim6.core.cpp:19275:68: error: use of undeclared identifier 'd_lln'
  dVth_ldop_Vdi_bi_Vdi_bi=(+0.0*bsim6_lln((Leff/T3))+(-nVt_Vdi_bi)*d_lln((Leff/T3),(-Leff*T3_Vdi_bi/T3/T3))+(-nVt_Vdi_bi)*bsim6_d_lln((Leff/T3),(-Leff*T3_Vdi_bi/T3/T3))+(-nVt)*(0.0/T3-(0.0*T3_Vdi_bi+0.0*T3_Vdi_bi+Leff*T3_Vdi_bi_Vdi_bi)/T3/T3+2*Leff*T3_Vdi_bi*T3_Vdi_bi/T3/T3/T3));

It is looking for the derivative of `bsim6_lln` which is `bsim6_d_lln`.