fix MinGW wrong isinf namespace
Some systems have isnan, isinf and isfinite in the std namespace, other don't.

See:
https://github.com/brechtvl/oiio/commit/b02f661bcc5cb8ead2a2a3f5c9a465d8eb1ba8a8

TODO - Need to cross check on Linux, OSX

Error:
```
In file included from ../../../src/components/component.h:35:0,
                 from cpwline.cpp:30:
cpwline.cpp: In static member function 'static void cpwline::ellipke(double, double&, double&)':
../../../src/compat.h:47:20: error: expected unqualified-id before '(' token
 # define isinf(x)  (!_finite(x) && !_isnan(x))
                    ^
cpwline.cpp:54:17: note: in expansion of macro 'isinf'
   else if (std::isinf (arg) && arg < 0) {
                 ^
make[4]: *** [cpwline.lo] Error 1
```