Revert "do the first component loop"
This reverts commit 2c69c195fce31a1862eba511f213e304f3d0fdf8.

Error: OSX, Qt5.11.1

/usr/local/opt/qt/lib/QtCore.framework/Headers/qlist.h:462:34: error: call to implicitly-deleted copy constructor of
      'Component'
                current->v = new T(*reinterpret_cast<T*>(src->v));
                                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~